site_name: NearIT iOS
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
extra_javascript : ["js/extra.js"]
pages:
    - 'Getting started' : 'index.md'
    - 'User Guide' :
        - 'Installation' : 'installation.md'
        - 'Notification Setup' : 'setup-notifications.md'
        - 'Location Based Notifications' : 'location-based-notifications.md'
        - 'Push Notifications' : 'push-notifications.md'
        - 'In-App Events' : 'in-app-events.md'
        - 'In-app Content' : 'handle-content.md'
        - 'User Profiling & Opt-out' : 'user-profiling.md'
        - 'Before you release' : 'before-you-release.md'
    - 'Other resources' :
        - 'Customize Notifications' : 'customize-notifications.md'
        - 'Logging' : 'logging.md'
