# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearSample
  pod 'NearITSDKSwift', '~> 2.9.5'
  pod 'NearUIBinding'

# Utility pod
pod 'Hex'

end
